### ISSUE TITLE
add some kind of 'find' wrapper ?

### ISSUE THREAD

**Issue by weepy** [creationix/nstore#1]
It would be handy to have a shortcut for the find stuff. E.g. something like

<pre>
users.find(function(doc, meta) {
   return doc.age > 18 && doc.age < 40;
}, function(results) { 
  // Do something with all the documents
})
</pre>

**Comment by creationix** [comment]
That's what the `all()` function does.

**Comment by creationix** [comment]
Oh, I see, it's not in the docs.  Will add...

**Comment by weepy** [comment]
your addition to the docs is says "stream" rather than "all"  ?

**Comment by creationix** [comment]
Thanks.  It was a very busy day yesterday.  I released 2.5 projects.

**Comment by creationix** [comment]
I assume this issue is resolved now.
