### ISSUE TITLE
Fails to load modules

### ISSUE THREAD

**Issue by jankolkmeier** [creationix/nstore#16]
nStore@0.3.0 fails on the lines 
    Hash = require('pattern/hash'),
    Queue = require('pattern/queue'),

I don't know if this is a packaging issue on nStore or on pattern.
Using node@v0.2.4.

**Comment by jankolkmeier** [comment]
Similar problem when trying to extend nStore:
instead of:
    nStore  = require('nstore').extend(require('nstore/query')()),
i have to do:
    nStore  = require('nstore').extend(require('/usr/local/lib/node/.npm/nstore/active/package/lib/nstore/query')()),

**Comment by creationix** [comment]
Fixed now.  pattern and nstore both work with latest npm.
