### ISSUE TITLE
clear() doesn't do anything

### ISSUE THREAD

**Issue by virtuo** [creationix/nstore#2]
I might be misleading on the semantic of clear, but it seems it doesn't do anything (at least when this is the first operation applied on a newly loaded store). Shouldn't it empty the store?

**Comment by creationix** [comment]
It should yes, I'll look into this.

**Comment by creationix** [comment]
I fixed a bug in remove recently.  Also I added a unit test for clear.  it seems to be working now.

**Comment by creationix** [comment]
Closing this issue.  If it's still broken for you, please re-open.
