### ISSUE TITLE
TypeError: Object #<initialize> has no method 'loadDatabase'

### ISSUE THREAD

**Issue by amper5and** [creationix/nstore#23]
I'm new to Node.js, but I'm sure I installed this module correctly using npm 1.0.5 on node 0.4.7. However, when I try the examples, I get TypeError: Object # &lt; initialize &gt; has no method 'loadDatabase'.

Is it incompatible w/ 0.4.7 or is there something else I need to do to fix this?

**Comment by jankolkmeier** [comment]
I wasn't able to install anything with npm, so I cloned nstore and all its dependencies by hand and modified the require paths.

Now ran into the same problem.

**Comment by gaara87** [comment]
i got the same thing tooo

**Comment by creationix** [comment]
Seems to be a bug in the pattern dependency.  I removed the hacks from pattern and it seems to be working now.

**Comment by gaara87** [comment]
thats great thank you so much!

On Saturday 09 July 2011 04:08 AM, creationix wrote:

> Seems to be a bug in the pattern dependency.  I removed the hacks from pattern and it seems to be working now.

## 

Akash Ramani
Director - Solutions Architect
Nutrix Tech Pvt. Ltd.
www.nutrixtech.com
