### ISSUE TITLE
nstore module not loading

### ISSUE THREAD

**Issue by gaara87** [creationix/nstore#24]
var nStore = require('nstore'); --> leads to the following error -->
"node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
Error: Cannot find module 'nstore'
    at Function._resolveFilename (module.js:322:11)
    at Function._load (module.js:267:25)
    at require (module.js:351:19)
    at Object.<anonymous> (/home/gaara/workspace/powercuts/datacruncher.js:1:76)
    at Module._compile (module.js:407:26)
    at Object..js (module.js:413:10)
    at Module.load (module.js:339:31)
    at Function._load (module.js:298:12)
    at Array.<anonymous> (module.js:426:10)
    at EventEmitter._tickCallback (node.js:126:26)"

Any idea what the problem is ? Every other module loads just fine without a problem. 

Thanks in advance

**Comment by creationix** [comment]
How did you install nstore?  Also I think that NPM changed a while back and broke any package that used the recommended "modules" hash.  I believe nStore is one of those.

**Comment by gaara87** [comment]
yep i installed it through npm. Aha, so what is the workaround for this 
break? any idea?

thanks

On Tuesday 05 July 2011 11:04 PM, creationix wrote:

> How did you install nstore?  Also I think that NPM changed a while back and broke any package that used the recommended "modules" hash.  I believe nStore is one of those.

## 

Akash Ramani
Director - Solutions Architect
Nutrix Tech Pvt. Ltd.
www.nutrixtech.com

**Comment by gaara87** [comment]
so...whats the work around? couldn't really figure it out from what was posted in the other issues

**Comment by gaara87** [comment]
Ok i've tried every other simple stand alone store out there including leveldb and nstore seems to be the most direct and straightforward, EXCEPT for the fact that it doesnt work :S

i've tried patching it myself but it seems to be failing miserably. probably because i din't really go through the code completely. I would be highly obliged and thankful if there is a quick work around for me to get this working. 

If there isn't can you suggest a better alternative? 

Thanks

**Comment by creationix** [comment]
Sure, I can get it working if you really want nStore.  What's your use case?

**Comment by creationix** [comment]
Try it now.  I can npm install nstore and everything seem to be working as before.  Though, the remove unit test is still failing like before.

**Comment by gaara87** [comment]
Thanks m8!

Its a simple use case of broadcasting power cuts information. So all i 
need is a mapping of phone numbers to location. For which i could have 
used dirty or chaos, but they dont store objects too well..

again. Thanks :)

On Friday 08 July 2011 09:18 PM, creationix wrote:

> Sure, I can get it working if you really want nStore.  What's your use case?

## 

Akash Ramani
Director - Solutions Architect
Nutrix Tech Pvt. Ltd.
www.nutrixtech.com
