### ISSUE TITLE
difference between this and node-dirty

### ISSUE THREAD

**Issue by weepy** [creationix/nstore#9]
hey -- they look quite similar -- be useful to see how they differ ?

**Comment by creationix** [comment]
Basically, node-dirty came first.  It is super minimal and has a limited scope as a feature.  nStore is a project to build on the ideas in node-dirty combined with the ideas from couchdb and other data stores to build a production class database in node.js.  

The current version is mostly stable and has some nice features.  It's probably about at the level of node-dirty, but with slightly different features. (not all data is kept in ram)

After the next rewrite, nStore will be based on b+trees and support storing binary data.

**Comment by ghost** [comment]
creationix:  What you've said is quite different from what it says in the README:

> Warning
> 
> This library is still under development. There are bugs. APIs will change. Docs may be wrong.
> 
> Keep in mind this is something I make in my free time and that's something I've had very little of lately thanks to my many other projects. I would love for someone with database and javascript smarts to partner with to make nStore super awesome.

**Comment by ghost** [comment]
What I mean is: that warning is quite scary (I hadn't been using nStore because of it, in fact) and doesn't seem to apply to the present state of nStore.

**Comment by creationix** [comment]
The warning is meant to scare people away.  I actually haven't used the current version in production.  In my minimal testing it worked, but it was minimal.

**Comment by creationix** [comment]
other than one of the unit tests not working, this seems fairly stable.  I'd would test more before using though.
